### ISSUE TITLE
Getting error `tutor images build openedx `

### ISSUE THREAD

**Issue by wiesener** [aulasneo/tutor-contrib-branding#6]
=> ERROR [production 36/39] RUN npm run compile-sass -- --skip-default                                                                        0.5s
------
 > [production 36/39] RUN npm run compile-sass -- --skip-default:
0.394 
0.394 > edx@0.1.0 compile-sass
0.394 > scripts/compile_sass.py --env=${NODE_ENV:-production} --skip-default
0.394 
0.438 USING ENV: production
0.438 
0.438 
0.439 Compiling Sass for theme at /openedx/themes/theme...
0.439   Compiling default LMS Sass with themed partials...
0.439     Source: lms/static/sass
0.439     Target: /openedx/themes/theme/lms/static/css
0.439     Include paths:
0.439       common/static
0.439       common/static/sass
0.439       node_modules/@edx
0.439       node_modules
0.439       /openedx/themes/theme/lms/static/sass/partials
0.439       lms/static/sass/partials
0.439       lms/static/sass
0.439     Files:
0.439       lms/static/sass/lms-course-rtl.scss -> /openedx/themes/theme/lms/static/css/lms-course-rtl.css
0.505 Traceback (most recent call last):
0.505   File "/openedx/edx-platform/scripts/compile_sass.py", line 503, in <module>
0.506     main(prog_name="npm run compile-sass --")
0.506   File "/openedx/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
0.506     return self.main(*args, **kwargs)
0.506            ^^^^^^^^^^^^^^^^^^^^^^^^^^
0.506   File "/openedx/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
0.506     rv = self.invoke(ctx)
0.506          ^^^^^^^^^^^^^^^^
0.506   File "/openedx/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
0.506     return ctx.invoke(self.callback, **ctx.params)
0.506            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.506   File "/openedx/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
0.507     return __callback(*args, **kwargs)
0.507            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.507   File "/openedx/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
0.507     return f(get_current_context(), *args, **kwargs)
0.507            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.507   File "/openedx/edx-platform/scripts/compile_sass.py", line 397, in main
0.507     compile_sass_dir(
0.507   File "/openedx/edx-platform/scripts/compile_sass.py", line 252, in compile_sass_dir
0.507     raise Exception(f"Failed to compile {source}: {output_text}")
0.507 Exception: Failed to compile lms/static/sass/lms-course-rtl.scss: Error: argument `$color` of `darken($color, $amount)` must be a color
0.507 
0.507        Backtrace:
0.507        	node_modules/bootstrap/scss/_variables.scss:152, in function `darken`
0.507        	node_modules/bootstrap/scss/_variables.scss:152
0.507         on line 152 of node_modules/bootstrap/scss/_variables.scss
0.507 >> $link-hover-color:          darken($link-color, 15%) !default;
0.507    ----------------------------^
0.507 
------
Dockerfile:220
--------------------
 218 |     # Now that the default theme is built, build any custom themes
 219 |     COPY --chown=app:app ./themes/ /openedx/themes
 220 | >>> RUN npm run compile-sass -- --skip-default
 221 |     
 222 |     # and finally, collect assets for the production image,
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run compile-sass -- --skip-default" did not complete successfully: exit code: 1
Error: Command failed with status 1: docker buildx build --tag=docker.io/overhangio/openedx:18.1.3-indigo --output=type=docker --cache-from=type=registry,ref=docker.io/overhangio/openedx:18.1.3-indigo-cache /Users/xxx/Library/Application Support/tutor/env/build/openedx

My config looks like this:

BRANDING_ACCENT_A: #00BBF9
BRANDING_ACCENT_B: #FFEE88
BRANDING_BACKGROUND: #ffffff
BRANDING_BG_PRIMARY: #ffffff
BRANDING_BODY: #FFFFFF
BRANDING_BRAND: #9D0054
BRANDING_DANGER: #C32D3A
BRANDING_DARK: #273F2F
BRANDING_FONTS_URLS:
- https://fonts.google.com/download?family=Roboto%20Flex
BRANDING_FONT_FAMILY: Roboto Flex
BRANDING_HOMEPAGE_BG_IMAGE: ""
BRANDING_INFO: #006DAA
BRANDING_LIGHT: #E1DDDB
BRANDING_PRIMARY: #0000FF
BRANDING_SECONDARY: #454545
BRANDING_SUCCESS: #178253
BRANDING_WARNING: #FFD900
CMS_HOST: studio.local.edly.io
CMS_OAUTH2_SECRET: xxx
CONTACT_EMAIL: contact@local.edly.io
ENABLE_HTTPS: false
ID: d6yCxRxEjzbk9MNMrDhO0HKJ
JWT_RSA_PRIVATE_KEY: '
...
  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.edly.io
MYSQL_ROOT_PASSWORD: x49UV07H
OPENEDX_MYSQL_PASSWORD: F5Y6vzm2
OPENEDX_SECRET_KEY: xxx
PLATFORM_NAME: My Open edX
PLUGINS:
- branding
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main

The tutor version is:

```
tutor, version 18.1.3
```

**Comment by angonz** [comment]
When you set colors with #, please enclose the value between quotes. Otherwise the compiler will treat the value as a comment. 
E.g.:
`BRANDING_ACCENT_A: "#00BBF9"`

Let me know if this fixes the issue.

**Comment by wiesener** [comment]
Okay I've tried with a clean config

```
BRANDING_ACCENT_A: null
BRANDING_ACCENT_B: null
BRANDING_BACKGROUND: null
BRANDING_BG_PRIMARY: null
BRANDING_BODY: null
BRANDING_BRAND: null
BRANDING_DANGER: null
BRANDING_DARK: null
BRANDING_FONTS_URLS:
BRANDING_FONT_FAMILY:
BRANDING_HOMEPAGE_BG_IMAGE: ''
BRANDING_INFO: null
BRANDING_LIGHT: null
BRANDING_PRIMARY: null
BRANDING_SECONDARY: null
BRANDING_SUCCESS: null
BRANDING_WARNING: null
CMS_HOST: studio.local.edly.io
CMS_OAUTH2_SECRET: xxx
CONTACT_EMAIL: contact@local.edly.io
ENABLE_HTTPS: false
ID: d6yCxRxEjzbk9MNMrDhO0HKJ
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----
...
  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.edly.io
MYSQL_ROOT_PASSWORD: xxx
OPENEDX_MYSQL_PASSWORD: xxx
OPENEDX_SECRET_KEY: xxx
PLATFORM_NAME: My Open edX
PLUGINS:
- branding
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
```
But still getting the same error.

**Comment by wiesener** [comment]
Any news regarding this issue?

**Comment by angonz** [comment]
It's the same. Don't use "null", as it is taken as a string and it is not a color. Just remove all the settings that you don't need, or use any color format accepted by scss. Just remember to enclose the color in quotes if you use # format.

**Comment by wiesener** [comment]
Okay but this is generated by default. So I did not take it but tutor generated it with your plugin. Could you maybe send a working config. I am a bit lost to get in the correct pathes and strings for colors.

**Comment by angonz** [comment]
Can you please show the steps you follow to get that configuration? Which versions of tutor and the plugins are you using? Neither Tutor nor any plugin should add any BRANDING_ setting by default to a clean config.

**Comment by wiesener** [comment]
I just installed tutor via pip and then installed your plugin and then I just ran the command 

```tutor local launch```

And afterwards I've stopped it with:

`tutor local stop`

And I've run your commands:

```
tutor images build openedx
tutor images build mfe
tutor local settheme theme
```

And then the error occurs. The tutor version is: 18.1.3 and the branding is the newest.

**Comment by wiesener** [comment]
Did you had time to check the issue?

**Comment by angonz** [comment]
I've gone through all your steps, and could not replicate the issue. Actually there is nothing there that can create any `BRANDING_` entry in the config file.
Just two things, if you use the tutor-contrib-branding plugin, you should not run the `settheme` command. Running the `tutor local do init [--limit branding]` will set the right theme for you.
If you don't use this plugin, remember that now `settheme` must be run after `tutor local do`.

**Comment by wiesener** [comment]
And do you have a config I can try?

**Comment by angonz** [comment]
No config. Just start from scratch. There should be no BRANDING_ entries in the config.yml. Settings like `BRANDING_ACCENT_A: null` and others break the asset compiling process.

**Comment by wiesener** [comment]
Okay and 

> tutor local do init [--limit branding]



> I've gone through all your steps, and could not replicate the issue. Actually there is nothing there that can create any `BRANDING_` entry in the config file. Just two things, if you use the tutor-contrib-branding plugin, you should not run the `settheme` command. Running the `tutor local do init [--limit branding]` will set the right theme for you. If you don't use this plugin, remember that now `settheme` must be run after `tutor local do`.

Okay, thanks I am going to try. But somehow I am not sure regarding the getting started in your documentation. There you ask the user to call:

```
tutor plugins enable branding
tutor branding download-images
tutor branding download-fonts
tutor images build openedx
tutor images build mfe
tutor local settheme theme
```

And I am definitely not sure which commands are needed to get a simple example running. Or if I set a new branding setting. Which commands I do have to run to check the change.

**Comment by wiesener** [comment]
Okay now I have a clean tutor installation with a clean config. Now if I add a setting according to your README I am getting:

```tutor config --set "BRANDING_PRIMARY=#0000FF"```

```
Usage: tutor config [OPTIONS] COMMAND [ARGS]...
Try 'tutor config -h' for help.

Error: No such option: --set
```

**Comment by angonz** [comment]
Only these you need to run:
```
tutor plugins enable branding
tutor images build openedx
tutor images build mfe
tutor local do init --limit branding
```

`download-images` and `download-fonts` are deprecated; the functionality is now part of the `init`. Same for `settheme`.

To set a variable run:
```
tutor config save --set "BRANDING_PRIMARY='#0000FF'"
```

Make sure that the `#0000FF` is enclosed in quotes inside `config.yml`.

**Comment by wiesener** [comment]
Okay thanks, If I change a variable what do I have to run to apply the change?

**Comment by angonz** [comment]
You will have to rebuild both openedx and mfe images.
Please let me know if it works.

**Comment by wiesener** [comment]
No it is not running:
```
ERROR: failed to solve: process "/bin/sh -c npm run webpack" did not complete successfully: exit code: 137
Error: Command failed with status 1: docker buildx build --tag=docker.io/overhangio/openedx:18.1.4-indigo --output=type=docker --cache-from=type=registry,ref=docker.io/overhangio/openedx:18.1.4-indigo-cache /Users/constantin/Library/Application Support/tutor/env/build/openedx
```

It is a clean installation the config is free of any BRANDING settings. I only enabled branding and then I tried:

```tutor images build openedx```

Do I have to stop all docker images?

Yes seems so. Maybe this needs to be added to the documentation.

**Comment by wiesener** [comment]
Okay for the mfe a different error:

```
> [discussions-common  5/12] RUN npm install '@edx/brand@file:/openedx/brand-openedx':
32.90 npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
37.59 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
38.52 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
39.30 npm notice 
39.30 npm notice New minor version of npm available! 10.2.3 -> 10.9.0
39.30 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.9.0>
39.30 npm notice Run `npm install -g npm@10.9.0` to update!
39.30 npm notice 
39.32 npm ERR! code ECONNRESET
39.34 npm ERR! network aborted
39.35 npm ERR! network This is a problem related to network connectivity.
39.35 npm ERR! network In most cases you are behind a proxy or have bad network settings.
39.35 npm ERR! network 
39.35 npm ERR! network If you are behind a proxy, please make sure that the
39.35 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
39.96 
39.96 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-11-15T15_14_02_865Z-debug-0.log
------
Dockerfile:254
--------------------
 252 |     COPY ./brand-openedx /openedx/brand-openedx
 253 |     
 254 | >>> RUN npm install '@edx/brand@file:/openedx/brand-openedx'
 255 |     
 256 |     ENV CPPFLAGS=-DPNG_ARM_NEON_OPT=0
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install '@edx/brand@file:/openedx/brand-openedx'" did not complete successfully: exit code: 1
Error: Command failed with status 1: docker buildx build --tag=docker.io/overhangio/openedx-mfe:18.0.1-indigo --output=type=docker --cache-from=type=registry,ref=docker.io/overhangio/openedx-mfe:18.0.1-indigo-cache /Users/xxx/Library/Application Support/tutor/env/plugins/mfe/build/mfe
```

**Comment by wiesener** [comment]
No still the same error for mfe build:

```
> [discussions-common  5/12] RUN npm install '@edx/brand@file:/openedx/brand-openedx':
75.98 npm WARN deprecated core-js@3.21.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
76.00 npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
173.0 npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
174.2 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
176.9 npm WARN deprecated babel-plugin-react-intl@8.2.25: this package has been renamed to babel-plugin-formatjs
186.3 npm WARN deprecated intl-messageformat-parser@6.1.2: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
193.3 npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
193.8 npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
195.1 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
212.4 npm WARN deprecated domexception@2.0.1: Use your platform's native DOMException instead
218.8 npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
218.9 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
226.7 npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
245.4 npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
251.2 npm WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
280.2 npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
281.9 npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
285.9 npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
294.7 npm notice 
294.7 npm notice New minor version of npm available! 10.2.3 -> 10.9.0
294.7 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.9.0>
294.7 npm notice Run `npm install -g npm@10.9.0` to update!
294.7 npm notice 
294.7 npm ERR! code ECONNRESET
294.7 npm ERR! network aborted
294.7 npm ERR! network This is a problem related to network connectivity.
294.7 npm ERR! network In most cases you are behind a proxy or have bad network settings.
294.7 npm ERR! network 
294.7 npm ERR! network If you are behind a proxy, please make sure that the
294.7 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
294.7 
294.7 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-11-15T15_15_54_217Z-debug-0.log
------
Dockerfile:254
--------------------
 252 |     COPY ./brand-openedx /openedx/brand-openedx
 253 |     
 254 | >>> RUN npm install '@edx/brand@file:/openedx/brand-openedx'
 255 |     
 256 |     ENV CPPFLAGS=-DPNG_ARM_NEON_OPT=0
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install '@edx/brand@file:/openedx/brand-openedx'" did not complete successfully: exit code: 1
Error: Command failed with status 1: docker buildx build --tag=docker.io/overhangio/openedx-mfe:18.0.1-indigo --output=type=docker --cache-from=type=registry,ref=docker.io/overhangio/openedx-mfe:18.0.1-indigo-cache /Users/xxx/Library/Application Support/tutor/env/plugins/mfe/build/mfe
```

**Comment by angonz** [comment]
It's not directly related to the plugin. It is because your docker is running out of resources or just stopped. Try again, and also check [this workaround](https://discuss.openedx.org/t/npm-err-code-err-socket-timeout-when-building-mfe-image/10414/3) to reduce the image building parallelism.

**Comment by wiesener** [comment]
Okay I've tried all work arounds but still getting this. Always at the same line:

```
 => ERROR [account-common  5/12] RUN npm install '@edx/brand@file:/openedx/brand-openedx'                                                                                       404.7s
```

```
403.8 npm ERR! code 1
403.8 npm ERR! path /openedx/app/node_modules/sharp
403.8 npm ERR! command failed
403.8 npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
403.8 npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-arm64v8.tar.br
403.8 npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
403.8 npm ERR! sharp: Installation error: connect ECONNREFUSED 140.82.121.3:443
```

I would say some dependencies could not be installed.

**Comment by wiesener** [comment]
I followed all steps of this issue: https://discuss.openedx.org/t/tutor-fails-when-build-mfe-images/11952/36
But still no progress. It seems that it has something to do with the branding plugin.
The change of the maxcpu eliminated the issue with installing sharp. But still it refuses to install.

**Comment by angonz** [comment]
The branding plugin causes the images to rebuild the assets, but the plugin is not the problem. It's a docker daemon issue when running npm install. It's a heavy process and consumes lots of resources.

**Comment by wiesener** [comment]
> The branding plugin causes the images to rebuild the assets, but the plugin is not the problem. It's a docker daemon issue when running npm install. It's a heavy process and consumes lots of resources.

Yes but I am gave the docker engine the maximum ressources available and it is still not running. I guess it is something else regarding the availability of some packages. So that it is more a network issue.

**Comment by angonz** [comment]
You must be running out of hardware resources. In an Core i9 Mac 16G I can build images having CPU limit at 8, mem limit at 8G and 4G swap, with max_parallelism at 1; and still many times it fails. Make sure that your computer doesn't sleep in the middle. In production we use a c7i.4xlarge just to build images, with maximum parallelism (rarely breaks).

If you are in the latest versions all packages must be available.

**Comment by wiesener** [comment]
I have Mac Pro M3 with 16G with docker at maximum and 4 G swap and it never builds:
Here ist my resource usage during build:

<img width="345" alt="grafik" src="https://github.com/user-attachments/assets/eb6c12f9-7af5-4ef0-aa10-9a0a6a3b96be">

There is not even a peek. So defenitly no resource issue. It has to be something else.
And it definitely says:

```
51.0 npm ERR! network aborted
151.0 npm ERR! network This is a problem related to network connectivity.
151.0 npm ERR! network In most cases you are behind a proxy or have bad network settings.
151.0 npm ERR! network 
151.0 npm ERR! network If you are behind a proxy, please make sure that the
151.0 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```
Which should indicate that it is something else than resources. But even at the university with 10 GLan same issue. So I would say it is something else.

**Comment by angonz** [comment]
I'm closing this ticket as the original issue is solved. If you need additional support please open a new request.
